"use client";

import { useWorkspaceQuery } from "@/components/providers";

import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/app-shell";
import { EmptyState, PageHeading } from "@/components/ui";
import { api } from "@/lib/api";
type Analytics={runStatuses:Array<{status:string;count:number}>;frameworks:Array<{framework:string;count:number}>;storage:Array<{project:string;datasets:number;bytes:number}>;metricNames:Array<{name:string;readings:number}>};const colors=["#7357f6","#ff6d3f","#54c7ec","#b7ed5a","#f6c453"];
export default function AnalyticsPage(){const{data}=useWorkspaceQuery({queryKey:["analytics"],queryFn:()=>api<Analytics>("/analytics")});const hasData=!!data&&(data.runStatuses.length+data.frameworks.length+data.storage.length>0);return <AppShell><PageHeading eyebrow="Patterns, not noise" title="Analytics" description="Understand how you work: model frameworks, run outcomes, data footprint, and the metrics you record most."/>{hasData?<div className="analytics-grid"><article className="panel analytics-panel"><div className="panel-header"><div><h2 className="panel-title">Run outcomes</h2><p className="panel-subtitle">Distribution by current status</p></div></div><div className="analytics-chart"><ResponsiveContainer><PieChart><Pie data={data.runStatuses} dataKey="count" nameKey="status" innerRadius={55} outerRadius={85} paddingAngle={4}>{data.runStatuses.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={{border:0,borderRadius:12,fontSize:11}}/></PieChart></ResponsiveContainer></div><div className="legend">{data.runStatuses.map((item,i)=><span key={item.status}><i style={{background:colors[i%colors.length]}}/>{item.status} · {item.count}</span>)}</div></article><article className="panel analytics-panel"><div className="panel-header"><div><h2 className="panel-title">Framework mix</h2><p className="panel-subtitle">Registered models by framework</p></div></div><div className="analytics-chart"><ResponsiveContainer><BarChart data={data.frameworks} margin={{top:10,right:15,left:-20,bottom:5}}><CartesianGrid vertical={false} strokeDasharray="3 6" stroke="#dedbe8"/><XAxis dataKey="framework" tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{border:0,borderRadius:12,fontSize:11}}/><Bar dataKey="count" fill="#7357f6" radius={[8,8,2,2]}/></BarChart></ResponsiveContainer></div></article><article className="panel analytics-panel wide"><div className="panel-header"><div><h2 className="panel-title">Dataset footprint</h2><p className="panel-subtitle">Bytes referenced by project</p></div></div><div className="analytics-chart"><ResponsiveContainer><BarChart data={data.storage} layout="vertical" margin={{top:5,right:25,left:15,bottom:5}}><CartesianGrid horizontal={false} strokeDasharray="3 6" stroke="#dedbe8"/><XAxis type="number" tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="project" width={110} tick={{fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{border:0,borderRadius:12,fontSize:11}}/><Bar dataKey="bytes" fill="#ff6d3f" radius={[2,8,8,2]}/></BarChart></ResponsiveContainer></div></article></div>:<EmptyState title="No patterns to show yet" description="Once you add models, datasets, and runs, this page will summarize the shape of your workspace."/>}</AppShell>}
