"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Database, KeyRound, LockKeyhole, LogOut, Server, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/providers";
import { PageHeading } from "@/components/ui";
import { RecoverySettings } from "@/components/recovery-settings";
export default function SettingsPage(){const{user,logout}=useAuth();const router=useRouter();const[error,setError]=useState("");return <AppShell><PageHeading eyebrow="Account & security" title="Settings" description="A clear view of your account and the protections around your workspace."/>{error&&<p className="error-notice" role="alert">{error}</p>}<div className="settings-grid"><RecoverySettings /><section className="panel settings-panel"><h2>Profile</h2><div className="settings-avatar">{user?.displayName.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}</div><div><span>Name</span><strong>{user?.displayName}</strong></div><div><span>Email</span><strong>{user?.email}</strong></div><button className="secondary-button danger-text" onClick={()=>void logout().then(()=>router.push("/login")).catch(e=>setError(e.message))}><LogOut size={14}/> Sign out</button></section><section className="panel settings-panel"><h2>Security posture</h2>{[[LockKeyhole,"HttpOnly session cookie","Credentials never touch browser storage."],[KeyRound,"Argon2id password hashing","Passwords use a memory-hard modern hash."],[ShieldCheck,"CSRF and origin checks","Write actions require a rotating secure token."],[Database,"Per-user ownership","Every data query is scoped to your account."]].map(([Icon,title,copy])=><div className="security-row" key={String(title)}><span><Icon size={16}/></span><div><strong>{String(title)}</strong><small>{String(copy)}</small></div></div>)}</section><section className="panel settings-panel"><h2>Deployment map</h2><div className="deployment-row"><span><Server size={16}/></span><div><strong>Vercel</strong><small>Next.js interface and same-origin API proxy</small></div></div><div className="deployment-line"/><div className="deployment-row"><span><Server size={16}/></span><div><strong>Render</strong><small>FastAPI service, validation, and access control</small></div></div><div className="deployment-line"/><div className="deployment-row"><span><Database size={16}/></span><div><strong>Turso</strong><small>Managed libSQL database over an encrypted connection</small></div></div></section></div></AppShell>}
